version: '3.7'

services:
  postgres:
    image: postgres:16
    hostname: postgres
    restart: always
    environment: 
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    expose:
      - '5432'
    ports:
      - '5433:5432'
    volumes:
      - ./scripts/sql/students.sql:/docker-entrypoint-initdb.d/students.sql