version: '3'

services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=database_example
    container_name: "postgres"
    healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
            timeout: 20s
            retries: 10

  create-db:
    build: .
    volumes:
      - .:/app
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=database_example
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy