example_dbt_core:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5433
      user: user
      pass: password
      dbname: postgres
      schema: public
    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5433
      user: user
      pass: password
      dbname: postgres
      schema: public
  target: dev